#cloud-config
autoinstall:
  version: 1
  identity:
     hostname: ubuntu
     username: ubuntu
     password: $6$2Nl39NrB6MAyZODg$PvZG2zIQ/qZ8w0KiEQLYjObVeszKGZF8aCD5PV9jhvJRp5xptljthsjysqR6ouCknn2Ml69CxSAErEKnzX6Si.
  ssh:
     install-server: yes
     allow-pw: yes
  poweroff: shutdown